name = "MethodInSrc"
uuid = "c116309b-47aa-4bde-803c-ba7517b69216"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "1.0.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
Aqua = ">= 0.8"
InteractiveUtils = ">= 0"
JET = ">= 0.0"
Test = ">= 0.0"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
